external_nullifier = ""
identity_secret = ""
message_id = ""
path_indices = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
siblings = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
user_message_limit = ""
x = ""
